# Generated by Django 2.1.15 on 2021-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SisContadores',
            fields=[
                ('codigo', models.CharField(db_column='Código', max_length=50, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=0, default=0, max_digits=18)),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
                'db_table': 'SIS_CONTADORES',
                'managed': False,
            },
        ),
    ]
