# Generated by Django 2.1.15 on 2021-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccAsientos',
            fields=[
                ('id', models.CharField(db_column='ID', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('documentoid', models.CharField(blank=True, db_column='DocumentoID', max_length=10, null=True)),
                ('numero', models.CharField(db_column='Número', max_length=10)),
                ('fecha', models.DateTimeField(db_column='Fecha')),
                ('detalle', models.CharField(db_column='Detalle', max_length=100)),
                ('tipo', models.CharField(db_column='Tipo', max_length=10)),
                ('nota', models.CharField(blank=True, db_column='Nota', default='', max_length=1024, null=True)),
                ('anulado', models.BooleanField(db_column='Anulado', default=False)),
                ('pendiente', models.BooleanField(db_column='Pendiente', default=False)),
                ('creadopor', models.CharField(blank=True, db_column='CreadoPor', editable=False, max_length=15, null=True)),
                ('editadopor', models.CharField(blank=True, db_column='EditadoPor', editable=False, max_length=15, null=True)),
                ('anuladopor', models.CharField(blank=True, db_column='AnuladoPor', editable=False, max_length=15, null=True)),
                ('pcid', models.CharField(blank=True, db_column='PCID', default='', editable=False, max_length=50, null=True)),
                ('sucursalid', models.CharField(blank=True, db_column='SucursalID', editable=False, max_length=2, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True, db_column='CreadoDate', null=True)),
                ('editadodate', models.DateTimeField(auto_now=True, db_column='EditadoDate', null=True)),
                ('anuladodate', models.DateTimeField(blank=True, db_column='AnuladoDate', editable=False, null=True)),
                ('anuladonota', models.CharField(blank=True, db_column='AnuladoNota', editable=False, max_length=1024, null=True)),
                ('divisionid', models.CharField(blank=True, db_column='DivisiónID', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'db_table': 'ACC_ASIENTOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccAsientosDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursalid', models.CharField(blank=True, db_column='SucursalID', editable=False, max_length=2, null=True)),
                ('debito', models.BooleanField(db_column='Débito', default=False)),
                ('valor', models.DecimalField(db_column='Valor', decimal_places=4, default=0, max_digits=19)),
                ('detalle', models.CharField(blank=True, db_column='Detalle', default='', max_length=250, null=True)),
                ('pcid', models.CharField(blank=True, db_column='PCID', editable=False, max_length=50, null=True)),
                ('valor_base', models.DecimalField(blank=True, db_column='Valor_Base', decimal_places=4, max_digits=19, null=True)),
                ('creadopor', models.CharField(blank=True, db_column='CreadoPor', editable=False, max_length=15, null=True)),
                ('divisaid', models.CharField(blank=True, db_column='DivisaID', max_length=10, null=True)),
                ('cambio', models.DecimalField(db_column='Cambio', decimal_places=6, default=0, max_digits=12)),
                ('creadodate', models.DateTimeField(auto_now_add=True, db_column='CreadoDate', null=True)),
                ('secuencia', models.TextField(db_column='Secuencia')),
                ('registro', models.DecimalField(blank=True, db_column='Registro', decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Asiento detalle',
                'verbose_name_plural': 'Asientos detalle',
                'db_table': 'ACC_ASIENTOS_DT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccCuentas',
            fields=[
                ('id', models.CharField(db_column='ID', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Código', max_length=25)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('clase', models.CharField(db_column='Clase', max_length=2)),
                ('tipo', models.CharField(db_column='Tipo', max_length=10)),
                ('ruta', models.CharField(blank=True, db_column='Ruta', editable=False, max_length=1024, null=True)),
                ('orden', models.CharField(blank=True, db_column='Orden', editable=False, max_length=1024, null=True)),
                ('anulado', models.BooleanField(db_column='Anulado', default=False)),
                ('nota', models.CharField(blank=True, db_column='Nota', max_length=1024, null=True)),
                ('exportado', models.BooleanField(db_column='Exportado', default=False)),
                ('pcid', models.CharField(blank=True, db_column='PCID', default='', editable=False, max_length=50, null=True)),
                ('sucursalid', models.CharField(blank=True, db_column='SucursalID', editable=False, max_length=2, null=True)),
                ('creadopor', models.CharField(blank=True, db_column='CreadoPor', editable=False, max_length=15, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True, db_column='CreadoDate', null=True)),
                ('editadopor', models.CharField(blank=True, db_column='EditadoPor', editable=False, max_length=15, null=True)),
                ('editadodate', models.DateTimeField(auto_now=True, db_column='EditadoDate', null=True)),
                ('debitos', models.CharField(blank=True, db_column='Debitos', max_length=20, null=True)),
                ('creditos', models.CharField(blank=True, db_column='Creditos', max_length=20, null=True)),
                ('flujo_efectivo', models.DecimalField(blank=True, db_column='FlujoEfectivo', decimal_places=0, max_digits=1, null=True)),
                ('superavit', models.DecimalField(blank=True, db_column='SuperAvit', decimal_places=0, max_digits=1, null=True)),
                ('agrupado', models.BooleanField(blank=True, db_column='Agrupado', null=True)),
                ('estado_cuenta', models.BooleanField(blank=True, db_column='EstadoCuenta', default=False, null=True)),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contable',
                'db_table': 'ACC_CUENTAS',
                'managed': False,
            },
        ),
    ]
