# Generated by Django 2.1.15 on 2021-04-14 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleado', '0001_initial'),
        ('cliente', '0001_initial'),
        ('sistema', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('banco', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.CharField(blank=True, editable=False, max_length=1024, null=True)),
                ('ruta', models.CharField(blank=True, editable=False, max_length=1024, null=True)),
                ('clase', models.CharField(blank=True, choices=[('LISTA', 'LISTA'), ('ITEM', 'ITEM')], max_length=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Mantenimientos', 'MANTENIMIENTOS'), ('Documentos', 'DOCUMENTOS'), ('Procesos', 'PROCESOS'), ('Informes', 'INFORMES'), ('Seguridad', 'SEGURIDAD')], max_length=15, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('item_orden', models.IntegerField(blank=True, default=0, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('creadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('editadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True)),
                ('editadodate', models.DateTimeField(auto_now=True)),
                ('pcid', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.SegModulo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['item_orden'],
            },
        ),
        migrations.CreateModel(
            name='SegModuloGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('prioridad', models.IntegerField(blank=True, null=True)),
                ('creadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('editadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True)),
                ('editadodate', models.DateTimeField(auto_now=True)),
                ('pcid', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('grupos', models.ManyToManyField(to='auth.Group')),
                ('modulos', models.ManyToManyField(to='seguridad.SegModulo')),
            ],
            options={
                'verbose_name': 'Grupo de Módulos',
                'verbose_name_plural': 'Grupos de Módulos',
                'ordering': ['prioridad', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SegUsuarioFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Archivo Foto')),
                ('creadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True)),
                ('pcid', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Foto',
                'verbose_name_plural': 'Usuarios Foto',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='SegUsuarioParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creadopor', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('creadodate', models.DateTimeField(auto_now_add=True, null=True)),
                ('pcid', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_banco_id', to='banco.BanBancos', verbose_name='Cobranza')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_caja_id', to='banco.BanBancos', verbose_name='Factura')),
                ('cliente_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.CliGrupos')),
                ('division', models.ForeignKey(blank=True, db_column='DivisiónID', default='', max_length=10, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sistema.SisDivisiones')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empleado.EmpEmpleados')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.InvParametroBodegas')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema.SisSucursales')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Parametro',
                'verbose_name_plural': 'Usuario Parametros',
                'ordering': ['usuario'],
            },
        ),
    ]
