# Generated by Django 2.1.15 on 2021-04-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcrAcreedores',
            fields=[
                ('id', models.CharField(db_column='ID', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Código', max_length=15)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=50, null=True)),
                ('representante', models.CharField(blank=True, db_column='Representante', max_length=60, null=True)),
                ('terminoid', models.CharField(blank=True, db_column='TérminoID', max_length=10, null=True)),
                ('zonaid', models.CharField(blank=True, db_column='ZonaID', max_length=10, null=True)),
                ('telefono1', models.CharField(blank=True, db_column='Teléfono1', max_length=20, null=True)),
                ('telefono2', models.CharField(blank=True, db_column='Teléfono2', max_length=20, null=True)),
                ('telefono3', models.CharField(blank=True, db_column='Teléfono3', max_length=20, null=True)),
                ('telefono4', models.CharField(blank=True, db_column='Teléfono4', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Dirección', max_length=1024, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('www', models.CharField(blank=True, db_column='WWW', max_length=50, null=True)),
                ('nota', models.CharField(blank=True, db_column='Nota', max_length=1024, null=True)),
                ('ruc', models.CharField(blank=True, db_column='Ruc', max_length=13, null=True)),
                ('cedula', models.CharField(blank=True, db_column='Cédula', max_length=10, null=True)),
                ('clase', models.CharField(blank=True, db_column='Clase', max_length=2, null=True)),
                ('anulado', models.BooleanField(db_column='Anulado', default=False)),
                ('anuladopor', models.CharField(blank=True, db_column='AnuladoPor', editable=False, max_length=15, null=True)),
                ('creadopor', models.CharField(blank=True, db_column='CreadoPor', editable=False, max_length=15, null=True)),
                ('creadodate', models.DateTimeField(blank=True, db_column='CreadoDate', editable=False, null=True)),
                ('sucursalid', models.CharField(blank=True, db_column='SucursalID', editable=False, max_length=2, null=True)),
                ('pcid', models.CharField(blank=True, db_column='PcID', editable=False, max_length=50, null=True)),
                ('editadopor', models.CharField(blank=True, db_column='EditadoPor', editable=False, max_length=15, null=True)),
                ('editadodate', models.DateTimeField(blank=True, db_column='EditadoDate', editable=False, null=True)),
                ('secuenciaid', models.CharField(blank=True, db_column='SecuenciaID', editable=False, max_length=10, null=True)),
                ('utorizacion', models.CharField(blank=True, db_column='acrAutorizacion', max_length=100, null=True)),
                ('serie', models.CharField(blank=True, db_column='acrSerie', max_length=10, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, db_column='TipoCuenta', max_length=2, null=True)),
                ('cuenta', models.CharField(blank=True, db_column='Cuenta', max_length=50, null=True)),
                ('bancoid', models.CharField(blank=True, db_column='BancoID', max_length=10, null=True)),
                ('copia_email', models.CharField(blank=True, db_column='CopiaEmail', max_length=50, null=True)),
                ('tipo_acreedor', models.DecimalField(blank=True, db_column='TipoAcreedor', decimal_places=0, max_digits=1, null=True)),
                ('cta_contable', models.CharField(blank=True, db_column='CtaContable', max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Acreedor',
                'verbose_name_plural': 'Acreedores',
                'db_table': 'ACR_ACREEDORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcrGrupos',
            fields=[
                ('id', models.CharField(db_column='ID', editable=False, max_length=10, primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Código', max_length=15)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('orden', models.CharField(blank=True, db_column='Orden', editable=False, max_length=1024, null=True)),
                ('ruta', models.CharField(blank=True, db_column='Ruta', editable=False, max_length=1024, null=True)),
                ('anulado', models.BooleanField(db_column='Anulado', default=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=10)),
                ('creadopor', models.CharField(blank=True, db_column='CreadoPor', editable=False, max_length=15, null=True)),
                ('creadodate', models.DateTimeField(blank=True, db_column='CreadoDate', editable=False, null=True)),
                ('editadopor', models.CharField(blank=True, db_column='EditadoPor', editable=False, max_length=15, null=True)),
                ('editadodate', models.DateTimeField(blank=True, db_column='EditadoDate', editable=False, null=True)),
                ('sucursalid', models.CharField(blank=True, db_column='SucursalID', editable=False, max_length=2, null=True)),
                ('pcid', models.CharField(blank=True, db_column='PcID', editable=False, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Acreedor Grupo',
                'verbose_name_plural': 'Acreedor Grupos',
                'db_table': 'ACR_GRUPOS',
                'managed': False,
            },
        ),
    ]
